### ISSUE TITLE
Titles with hyphen builds with wrong anchor link

### ISSUE THREAD

**Issue by 1cgonza** [stuebersystems/gitbook-plugin-simple-page-toc#3]
```md
<!-- toc -->
## My title - with a hyphen
```
This will produce a TOC link where spaces around the hyphen are trimmed: 
```html 
<a href="#my-title-with-a-hyphen">My title - with a hyphen</a>
```

But in the body, the id has 3 hyphens (spaces are not trimmed but replaced with hyphens): 
```html
<h2 id="my-title---with-a-hyphen">My title - with a hyphen</h2>
```

The result is that the link gets created in the TOC, but doesn't work since the link and ID it should scroll to, are not the same.

Extra note, in the example I use h2, but the behavior persists regardless the h level.

**Comment by fstueber** [comment]
Hi. bug should be fixed now. See new version 0.1.2
